### PR TITLE
Added being able to pass previous_convo_id and conversation_id to ask()

### PR DESCRIPTION
**Pull request by Mazawrath**
This will do what was requested in #49.

### CODE REVIEW

**Comment by Mazawrath** [comment]
Unrelated to this pull request, but unless I'm doing something wrong, I can't get it to forget the context of previous messages, which I thought was what these values were related to.
I tried setting `previous_convo_id` and `conversation_id` to random values every new message, but it seems to remember messages that were said before anyways, even if those two values are totally different.
Would you be able to explain what these two values do? If they don't do what I think feel free to close this pull request.

**Comment by Mazawrath** [comment]
And that seems to have been caused by the oversight I fixed in above commit. Disregard that last comment.

**Comment by rawandahmad698** [comment]
Interesting. If you look at the actual API, the only tracking they use is parent_message_id and conversation_id.

**Comment by Mazawrath** [comment]
I was able to figure out all the values that I need to keep a conversation going. This will let you decide on the fly whether to keep the context of previous message not.

**Comment by rawandahmad698** [comment]
Thank you. Is it possible to add some docs on the Readme?

**Pull request merged**
